# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='comments',
        ),
        migrations.AddField(
            model_name='vote',
            name='comments',
            field=models.ManyToManyField(related_name='comment_votes', to='main.SMSResponse'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='reply_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='main.SMSResponse'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='sent_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='main.SMSMessage'),
        ),
    ]
