# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170727_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsresponse',
            options={'ordering': ['date']},
        ),
    ]
