# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170729_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hypo',
            options={'ordering': ['-send_time']},
        ),
    ]
