# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170729_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pseudonym',
            field=models.CharField(blank=True, default='Anonymous User', max_length=255, null=True, unique=True),
        ),
    ]
