# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 21:47
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170801_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_info',
            field=jsonfield.fields.JSONField(blank=True, max_length=255, null=True),
        ),
    ]
