# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170804_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnumber',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
