# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_smsnumber_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnumber',
            name='service',
            field=models.CharField(choices=[('plivo', 'plivo'), ('twilio', 'twilio')], default='plivo', max_length=10),
        ),
    ]
